import os, sys
import time
import datetime

show_dict = {'title': 'OBDM656 - Change Your Age | Right Wingers in Video Games | Serial Pooper',
             'title_detail': {'type': 'text/plain', 'language': None, 'base': 'http://ourbigdumbmouth.libsyn.com/rss',
                              'value': 'OBDM656 - Change Your Age | Right Wingers in Video Games | Serial Pooper'},
             'published': 'Sat, 10 Nov 2018 18:26:15 +0000',
             'published_parsed': None,
             'id': 'e8b25057bb6347e38c2e680e9d4337ae', 'guidislink': False, 'links': [
        {'rel': 'alternate', 'type': 'text/html',
         'href': 'http://ourbigdumbmouth.libsyn.com/obdm656-change-your-age-right-wingers-in-video-games-serial-pooper'},
        {'length': '31127408', 'type': 'audio/mpeg',
         'href': 'http://traffic.libsyn.com/ourbigdumbmouth/OBDM656.mp3?dest-id=35324', 'rel': 'enclosure'}],
             'link': 'http://ourbigdumbmouth.libsyn.com/obdm656-change-your-age-right-wingers-in-video-games-serial-pooper',
             'image': {
                 'href': 'http://static.libsyn.com/p/assets/b/c/b/c/bcbc0de9c39c524f/obdm_bright_itunes_coverart3_rune.jpg'},
             'summary': '<p>69-Year-Old Dutch Man Seeks To Change His Legal Age To 49<br /> https://www.npr.org/2018/11/08/665592537/69-year-old-dutch-man-seeks-to-change-his-legal-age-to-49</p> <p>Right-Wing Hate Groups Are Recruiting Video Gamers<br /> https://www.npr.org/2018/11/05/660642531/right-wing-hate-groups-are-recruiting-video-gamers</p> <p>Man Who Writes Bigfoot Erotica Now a U.S. Congressman<br /> https://www.thecut.com/2018/11/denver-riggleman-wins-his-congressional-race-virginia-midterms.html</p> <p>Seeking Bigfoot : VIDEO<br /> https://www.youtube.com/watch?v=FrVTi3YOyjY</p> <p>Supermum Sue Radford is celebrating the birth of her 21st baby and says it ‘will be her LAST’ after 12-minute labour<br /> https://www.thesun.co.uk/news/7705758/radford-britains-biggest-family-21st-baby-last-one/</p> <p>Serial pooper’ accused of breaking into Heights homes, cars<br /> https://www.click2houston.com/news/serial-pooper-accused-of-breaking-into-heights-homes-cars</p> <p>Why DARPA Is Betting a Million Bucks on an “Impossible” Space Drive<br /> https://www.popularmechanics.com/space/rockets/a24219132/darpa-emdrive/</p> <p>Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, comment, news reporting, teaching, scholarship, and research.<br /> ▀▄▀▄▀ LINKS ▀▄▀▄▀<br /> ► Phone: 614-388-9109<br /> ► Website: http://obdmpod.com<br /> ► Patreon: https://www.patreon.com/obdm<br /> ► YouTube: https://www.youtube.com/user/ourbigdumbmouth<br /> ► YouTube 2nd Channel: https://www.youtube.com/channel/UCrj4SPfo5ySkEnyaQAW5zvA<br /> ► Twitter: https://twitter.com/obdmpod<br /> ► Instagram: obdmpod<br /> ► RSS: http://ourbigdumbmouth.libsyn.com/rss<br /> ► iTunes: https://itunes.apple.com/us/podcast/our-big-dumb-mouth/id261189509?mt=2<br />  ► Twitter: https://twitter.com/obdmpod<br /> ► Facebook: https://www.facebook.com/obdmnews<br /> ► Everything we do could be considered performance art</p>',
             'summary_detail': {'type': 'text/html', 'language': None, 'base': 'http://ourbigdumbmouth.libsyn.com/rss',
                                'value': '<p>69-Year-Old Dutch Man Seeks To Change His Legal Age To 49<br /> https://www.npr.org/2018/11/08/665592537/69-year-old-dutch-man-seeks-to-change-his-legal-age-to-49</p> <p>Right-Wing Hate Groups Are Recruiting Video Gamers<br /> https://www.npr.org/2018/11/05/660642531/right-wing-hate-groups-are-recruiting-video-gamers</p> <p>Man Who Writes Bigfoot Erotica Now a U.S. Congressman<br /> https://www.thecut.com/2018/11/denver-riggleman-wins-his-congressional-race-virginia-midterms.html</p> <p>Seeking Bigfoot : VIDEO<br /> https://www.youtube.com/watch?v=FrVTi3YOyjY</p> <p>Supermum Sue Radford is celebrating the birth of her 21st baby and says it ‘will be her LAST’ after 12-minute labour<br /> https://www.thesun.co.uk/news/7705758/radford-britains-biggest-family-21st-baby-last-one/</p> <p>Serial pooper’ accused of breaking into Heights homes, cars<br /> https://www.click2houston.com/news/serial-pooper-accused-of-breaking-into-heights-homes-cars</p> <p>Why DARPA Is Betting a Million Bucks on an “Impossible” Space Drive<br /> https://www.popularmechanics.com/space/rockets/a24219132/darpa-emdrive/</p> <p>Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, comment, news reporting, teaching, scholarship, and research.<br /> ▀▄▀▄▀ LINKS ▀▄▀▄▀<br /> ► Phone: 614-388-9109<br /> ► Website: http://obdmpod.com<br /> ► Patreon: https://www.patreon.com/obdm<br /> ► YouTube: https://www.youtube.com/user/ourbigdumbmouth<br /> ► YouTube 2nd Channel: https://www.youtube.com/channel/UCrj4SPfo5ySkEnyaQAW5zvA<br /> ► Twitter: https://twitter.com/obdmpod<br /> ► Instagram: obdmpod<br /> ► RSS: http://ourbigdumbmouth.libsyn.com/rss<br /> ► iTunes: https://itunes.apple.com/us/podcast/our-big-dumb-mouth/id261189509?mt=2<br />  ► Twitter: https://twitter.com/obdmpod<br /> ► Facebook: https://www.facebook.com/obdmnews<br /> ► Everything we do could be considered performance art</p>'},
             'content': [{'type': 'text/html', 'language': None, 'base': 'http://ourbigdumbmouth.libsyn.com/rss',
                          'value': '<p>69-Year-Old Dutch Man Seeks To Change His Legal Age To 49 https://www.npr.org/2018/11/08/665592537/69-year-old-dutch-man-seeks-to-change-his-legal-age-to-49</p> <p>Right-Wing Hate Groups Are Recruiting Video Gamers https://www.npr.org/2018/11/05/660642531/right-wing-hate-groups-are-recruiting-video-gamers</p> <p>Man Who Writes Bigfoot Erotica Now a U.S. Congressman https://www.thecut.com/2018/11/denver-riggleman-wins-his-congressional-race-virginia-midterms.html</p> <p>Seeking Bigfoot : VIDEO https://www.youtube.com/watch?v=FrVTi3YOyjY</p> <p>Supermum Sue Radford is celebrating the birth of her 21st baby and says it ‘will be her LAST’ after 12-minute labour https://www.thesun.co.uk/news/7705758/radford-britains-biggest-family-21st-baby-last-one/</p> <p>Serial pooper’ accused of breaking into Heights homes, cars https://www.click2houston.com/news/serial-pooper-accused-of-breaking-into-heights-homes-cars</p> <p>Why DARPA Is Betting a Million Bucks on an “Impossible” Space Drive https://www.popularmechanics.com/space/rockets/a24219132/darpa-emdrive/</p> <p>Copyright Disclaimer Under Section 107 of the Copyright Act 1976, allowance is made for "fair use" for purposes such as criticism, comment, news reporting, teaching, scholarship, and research. ▀▄▀▄▀ LINKS ▀▄▀▄▀ ► Phone: 614-388-9109 ► Website: http://obdmpod.com ► Patreon: https://www.patreon.com/obdm ► YouTube: https://www.youtube.com/user/ourbigdumbmouth ► YouTube 2nd Channel: https://www.youtube.com/channel/UCrj4SPfo5ySkEnyaQAW5zvA ► Twitter: https://twitter.com/obdmpod ► Instagram: obdmpod ► RSS: http://ourbigdumbmouth.libsyn.com/rss ► iTunes: https://itunes.apple.com/us/podcast/our-big-dumb-mouth/id261189509?mt=2  ► Twitter: https://twitter.com/obdmpod ► Facebook: https://www.facebook.com/obdmnews ► Everything we do could be considered performance art</p>'}],
             'itunes_duration': '01:04:51', 'itunes_explicit': True,
             'subtitle': '69-Year-Old Dutch Man Seeks To Change His Legal Age To 49 https://www.npr.org/2018/11/08/665592537/69-year-old-dutch-man-seeks-to-change-his-legal-age-to-49 Right-Wing Hate Groups Are Recruiting Video Gamers...',
             'subtitle_detail': {'type': 'text/plain', 'language': None,
                                 'base': 'http://ourbigdumbmouth.libsyn.com/rss',
                                 'value': '69-Year-Old Dutch Man Seeks To Change His Legal Age To 49 https://www.npr.org/2018/11/08/665592537/69-year-old-dutch-man-seeks-to-change-his-legal-age-to-49 Right-Wing Hate Groups Are Recruiting Video Gamers...'},
             'itunes_episodetype': 'full'}

show_links = [{'rel': 'alternate', 'type': 'text/html',
               'href': 'http://ourbigdumbmouth.libsyn.com/obdm656-change-your-age-right-wingers-in-video-games-serial-pooper'},
              {'length': '31127408', 'type': 'audio/mpeg',
               'href': 'http://traffic.libsyn.com/ourbigdumbmouth/OBDM656.mp3?dest-id=35324', 'rel': 'enclosure'}]


print(show_dict['links'][1]['href'])
